<?php

function admin_demo_subsidies(): array
{
    return [
        [
            'id' => 1001,
            'name' => 'PM Kisan Samman Nidhi',
            'name_gu' => 'પીએમ કિસાન સન્માન નિધિ',
            'name_hi' => 'पीएम किसान सम्मान निधि',
            'category' => 'Income Support',
            'description' => 'Direct income support for eligible farmer families through three installments each year.',
            'description_gu' => 'લાયક ખેડૂત પરિવારો માટે દર વર્ષે ત્રણ હપ્તા દ્વારા સીધી આવક સહાય.',
            'description_hi' => 'हर साल तीन किश्तों के माध्यम से पात्र किसान परिवारों को प्रत्यक्ष आय सहायता।',
            'benefits' => 'Rs. 6,000 per year paid in three equal installments.',
            'benefits_gu' => 'ત્રણ સમાન હપ્તામાં દર વર્ષે રૂ. 6000 ચૂકવવામાં આવે છે.',
            'benefits_hi' => 'तीन समान किश्तों में प्रति वर्ष 6000 रुपये का भुगतान।',
            'eligibility' => 'Landholding farmer families with valid Aadhaar and bank details.',
            'apply_link' => 'https://pmkisan.gov.in/',
            'status' => 'Live',
            'last_updated' => '2026-03-12T00:00:00+05:30',
        ],
        [
            'id' => 1002,
            'name' => 'PM Fasal Bima Yojana',
            'name_gu' => 'પીએમ પાક વીમા યોજના',
            'name_hi' => 'पीएम फसल बीमा योजना',
            'category' => 'Income Support',
            'description' => 'Crop insurance support for notified crops affected by weather events, pests, and diseases.',
            'description_gu' => 'હવામાનની ઘટનાઓ છોડના રોગો વગેરેથી અસરગ્રસ્ત પાક માટે પાક વીમા સહાય.',
            'description_hi' => 'मौसम की घटनाओं, कीटों और बीमारियों से प्रभावित फसलों के लिए फसल बीमा सहायता।',
            'benefits' => 'Low farmer premium with claim support on insured crop loss.',
            'benefits_gu' => 'વીમા પાક નુકસાન પર દાવા સહાય સાથે ખેડૂત પ્રીમિયમ ઓછું.',
            'benefits_hi' => 'बीमित फसल हानि पर दावा समर्थन के साथ कम किसान प्रीमियम।',
            'eligibility' => 'Farmers growing notified crops in covered areas.',
            'apply_link' => 'https://pmfby.gov.in/',
            'status' => 'Live',
            'last_updated' => '2026-02-28T00:00:00+05:30',
        ],
        [
            'id' => 1003,
            'name' => 'Kisan Credit Card',
            'name_gu' => 'કિસાન ક્રેડિટ કાર્ડ',
            'name_hi' => 'किसान क्रेडिट कार्ड',
            'category' => 'Income Support',
            'description' => 'Short-term working capital support for crop production and allied farm activities.',
            'description_gu' => 'પાક ઉત્પાદન અને સંબંધિત ખેતી પ્રવૃત્તિઓ માટે ટૂંકા ગાળાની કાર્યકારી મૂડી સહાય.',
            'description_hi' => 'फसल उत्पादन और संबद्ध कृषि गतिविधियों के लिए अल्पकालिक कार्यशील पूंजी सहायता।',
            'benefits' => 'Access to low-interest crop loans and flexible seasonal credit.',
            'benefits_gu' => 'ઓછા વ્યાજની પાક લોન અને મોસમી ક્રેડિટની ઍક્સેસ.',
            'benefits_hi' => 'कम ब्याज वाले फसल ऋण और लचीले मौसमी ऋण तक पहुंच।',
            'eligibility' => 'Farmers, tenant farmers, sharecroppers, and eligible joint borrowers.',
            'apply_link' => 'https://www.nabard.org/',
            'status' => 'Live',
            'last_updated' => '2026-01-20T00:00:00+05:30',
        ],
        [
            'id' => 1004,
            'name' => 'Pradhan Mantri Krishi Sinchai Yojana',
            'name_gu' => 'પ્રધાનમંત્રી કૃષિ સિંચાઈ યોજના',
            'name_hi' => 'प्रधानमंत्री कृषि सिंचाई योजना',
            'category' => 'Irrigation',
            'description' => 'Support for micro-irrigation and better water-use efficiency at farm level.',
            'description_gu' => 'માઇક્રો-ઇરિગેશન અને ખેતર સ્તરે પાણી-ઉપયોગની કાર્યક્ષમતા માટે આધાર.',
            'description_hi' => 'सूक्ष्म सिंचाई और खेत स्तर पर बेहतर जल-उपयोग दक्षता के लिए समर्थन।',
            'benefits' => 'Subsidy support for drip and sprinkler systems, often 45% to 55% of cost.',
            'benefits_gu' => 'ડ્રિપ અને સ્પ્રિંકલર સિસ્ટમ માટે સબસિડી સપોર્ટ (45% થી 55% કિંમત).',
            'benefits_hi' => 'ड्रिप और स्प्रिंकलर सिस्टम के लिए सब्सिडी सहायता।',
            'eligibility' => 'Farmers applying through approved state agriculture or horticulture channels.',
            'apply_link' => 'https://pmksy.gov.in/',
            'status' => 'Live',
            'last_updated' => '2026-03-05T00:00:00+05:30',
        ],
        [
            'id' => 1005,
            'name' => 'Sub-Mission on Agricultural Mechanization',
            'name_gu' => 'કૃષિ મિકેનાઇઝેશન પર સબ-મિશન',
            'name_hi' => 'कृषि यंत्रीकरण पर उप-मिशन',
            'category' => 'Equipment',
            'description' => 'Capital support for selected farm machinery, implements, and custom hiring centers.',
            'description_gu' => 'પસંદ કરેલ ખેત મશીનરી, સાધનો માટે મૂડી સહાય.',
            'description_hi' => 'चयनित कृषि मशीनरी, उपकरणों के लिए पूंजी सहायता।',
            'benefits' => 'Subsidy on tractors, seed drills, planters, and other notified machinery.',
            'benefits_gu' => 'ટ્રેક્ટર, સીડ ડ્રીલ, પ્લાન્ટર્સ વગેરે મશીનરી પર સબસિડી.',
            'benefits_hi' => 'ट्रैक्टर, सीड ड्रिल, प्लांटर्स और अन्य अधिसूचित मशीनरी पर सब्सिडी।',
            'eligibility' => 'Individual farmers, FPOs, SHGs, and other approved entities.',
            'apply_link' => 'https://agrimachinery.nic.in/',
            'status' => 'Live',
            'last_updated' => '2026-02-14T00:00:00+05:30',
        ],
        [
            'id' => 1006,
            'name' => 'Gujarat iKhedut Assistance',
            'name_gu' => 'ગુજરાત આઈખેડૂત સહાય',
            'name_hi' => 'गुजरात आईखेडूत सहायता',
            'category' => 'Equipment',
            'description' => 'State-level assistance for farm equipment, horticulture inputs, and irrigation components.',
            'description_gu' => 'ખેત સાધનો, બાગાયત ઇનપુટ્સ અને સિંચાઈ ઘટકો માટે રાજ્ય-સ્તરની સહાય.',
            'description_hi' => 'कृषि उपकरणों, बागवानी इनपुट और सिंचाई घटकों के लिए राज्य स्तरीय सहायता।',
            'benefits' => 'Selected categories receive subsidy support on approved purchases and installations.',
            'benefits_gu' => 'પસંદ કરેલી શ્રેણીઓને મંજૂર ખરીદી પર સબસિડી સપોર્ટ મળે છે.',
            'benefits_hi' => 'चयनित श्रेणियों को अनुमोदित खरीद पर सब्सिडी समर्थन प्राप्त होता है।',
            'eligibility' => 'Registered farmers in Gujarat applying through the iKhedut portal.',
            'apply_link' => 'https://ikhedut.gujarat.gov.in/',
            'status' => 'Live',
            'last_updated' => '2026-03-18T00:00:00+05:30',
        ],
    ];
}

function admin_demo_pesticides(): array
{
    return [
        ['id' => 201, 'name' => 'Imidacloprid 17.8% SL', 'brand' => 'Confidor', 'price_range' => 'Rs. 450 - 700', 'target_pests' => 'Aphids, whitefly, jassids, thrips', 'usage_instructions' => 'Use at label rate with thorough foliar coverage.', 'category' => 'Insecticide'],
        ['id' => 202, 'name' => 'Thiamethoxam 25% WG', 'brand' => 'Actara', 'price_range' => 'Rs. 700 - 1100', 'target_pests' => 'Whitefly, aphids, leafhoppers', 'usage_instructions' => 'Apply at early infestation stage as per label guidance.', 'category' => 'Insecticide'],
        ['id' => 203, 'name' => 'Mancozeb 75% WP', 'brand' => 'Dithane M-45', 'price_range' => 'Rs. 220 - 420', 'target_pests' => 'Early blight, late blight, downy mildew', 'usage_instructions' => 'Protective spray at recommended interval when disease pressure starts.', 'category' => 'Fungicide'],
        ['id' => 204, 'name' => 'Copper Oxychloride 50% WP', 'brand' => 'Blitox', 'price_range' => 'Rs. 260 - 460', 'target_pests' => 'Bacterial leaf spot, downy mildew, leaf spot', 'usage_instructions' => 'Apply as a preventive or early curative spray.', 'category' => 'Fungicide'],
        ['id' => 205, 'name' => 'Carbendazim 50% WP', 'brand' => 'Bavistin', 'price_range' => 'Rs. 350 - 620', 'target_pests' => 'Powdery mildew, wilt, root rot', 'usage_instructions' => 'Use for foliar spray or soil drench depending on crop and disease.', 'category' => 'Systemic Fungicide'],
        ['id' => 206, 'name' => 'Propiconazole 25% EC', 'brand' => 'Tilt', 'price_range' => 'Rs. 600 - 920', 'target_pests' => 'Rust, leaf spot, sheath blight', 'usage_instructions' => 'Apply at disease onset and repeat only as needed.', 'category' => 'Fungicide'],
    ];
}

function admin_demo_pest_mappings(): array
{
    return [
        ['mapping_id' => 301, 'pest_name' => 'Aphids', 'effectiveness' => 'High', 'pesticide_id' => 201, 'name' => 'Imidacloprid 17.8% SL', 'brand' => 'Confidor', 'price_range' => 'Rs. 450 - 700', 'target_pests' => 'Aphids, whitefly, jassids, thrips', 'usage_instructions' => 'Use at label rate with thorough foliar coverage.'],
        ['mapping_id' => 302, 'pest_name' => 'Whitefly', 'effectiveness' => 'High', 'pesticide_id' => 202, 'name' => 'Thiamethoxam 25% WG', 'brand' => 'Actara', 'price_range' => 'Rs. 700 - 1100', 'target_pests' => 'Whitefly, aphids, leafhoppers', 'usage_instructions' => 'Apply at early infestation stage as per label guidance.'],
        ['mapping_id' => 303, 'pest_name' => 'Early Blight', 'effectiveness' => 'High', 'pesticide_id' => 203, 'name' => 'Mancozeb 75% WP', 'brand' => 'Dithane M-45', 'price_range' => 'Rs. 220 - 420', 'target_pests' => 'Early blight, late blight, downy mildew', 'usage_instructions' => 'Protective spray at recommended interval when disease pressure starts.'],
        ['mapping_id' => 304, 'pest_name' => 'Bacterial Leaf Spot', 'effectiveness' => 'High', 'pesticide_id' => 204, 'name' => 'Copper Oxychloride 50% WP', 'brand' => 'Blitox', 'price_range' => 'Rs. 260 - 460', 'target_pests' => 'Bacterial leaf spot, downy mildew, leaf spot', 'usage_instructions' => 'Apply as a preventive or early curative spray.'],
        ['mapping_id' => 305, 'pest_name' => 'Powdery Mildew', 'effectiveness' => 'High', 'pesticide_id' => 205, 'name' => 'Carbendazim 50% WP', 'brand' => 'Bavistin', 'price_range' => 'Rs. 350 - 620', 'target_pests' => 'Powdery mildew, wilt, root rot', 'usage_instructions' => 'Use for foliar spray or soil drench depending on crop and disease.'],
        ['mapping_id' => 306, 'pest_name' => 'Rust', 'effectiveness' => 'High', 'pesticide_id' => 206, 'name' => 'Propiconazole 25% EC', 'brand' => 'Tilt', 'price_range' => 'Rs. 600 - 920', 'target_pests' => 'Rust, leaf spot, sheath blight', 'usage_instructions' => 'Apply at disease onset and repeat only as needed.'],
    ];
}
