<?php

function admin_demo_subsidies(): array
{
    return [
        [
            'id' => 1001,
            'name' => 'Soil Health Card Scheme',
            'name_gu' => 'ભૂમિ આરોગ્ય કાર્ડ યોજના',
            'name_hi' => 'मृदा स्वास्थ्य कार्ड योजना',
            'category' => 'Training',
            'description' => 'Issues Soil Health Cards to farmers with crop-wise recommendations for nutrients.',
            'description_gu' => 'ખેડૂતોને તેમની જમીનની સ્થિતિ અનુસાર પાક માટે જરૂરી પોષક તત્ત્વોની ભલામણો સાથે ભૂમિ આરોગ્ય કાર્ડ આપવામાં આવે છે.',
            'description_hi' => 'किसानों को फसल-वार पोषक तत्वों की सिफारिशों के साथ मृदा स्वास्थ्य कार्ड जारी किए जाते हैं।',
            'benefits' => 'Free soil testing, personalized fertilizer recommendations, higher yields.',
            'benefits_gu' => 'નિઃશુલ્ક જમીન પરીક્ષણ, વ્યક્તિગત ખાતરની ભલામણો, વધુ ઉપજ.',
            'benefits_hi' => 'निःशुल्क मिट्टी परीक्षण, व्यक्तिगत उर्वरक सिफारिशें, उच्च उपज।',
            'apply_link' => 'https://soilhealth.dac.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1101,
            'name' => 'Gujarat Agriculture Subsidy Scheme (iKhedut)',
            'name_gu' => 'ગુજરાત આઈ-ખેડૂત સહાય યોજના',
            'name_hi' => 'गुजरात कृषि सब्सिडी योजना (iKhedut)',
            'category' => 'Equipment',
            'description' => 'Gujarat state scheme for agricultural inputs, mechanization, and horticulture development.',
            'description_gu' => 'ગુજરાત આઈ-ખેડૂત સહાય યોજના હેઠળ ખેડૂતોએ ખેતીના સાધનો, બાગાયત માટેની જરૂરી સામગ્રી અને સિંચાઈ ઘટકો માટે રાજ્ય સ્તરે સહાય મળે છે.',
            'description_hi' => 'कृषि इनपुट, मशीनीकरण और बागवानी विकास के लिए गुजरात राज्य की योजना।',
            'benefits' => 'Subsidies on seeds, fertilizers, drip irrigation, farm machinery (25-75%).',
            'benefits_gu' => 'બિયારણ, ખાતર, ટપક સિંચાઈ અને ખેતીની મશીનરી પર (25% થી 75%) સહાય.',
            'benefits_hi' => 'बीज, उर्वरक, ड्रिप सिंचाई, कृषि मशीनरी (25-75%) पर सब्सिडी।',
            'apply_link' => 'https://ikhedut.gujarat.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1201,
            'name' => 'Pradhan Mantri Krishi Sinchai Yojana (PMKSY)',
            'name_gu' => 'પ્રધાનમંત્રી કૃષિ સિંચાઈ યોજના (PMKSY)',
            'name_hi' => 'प्रधानमंत्री कृषि सिंचाई योजना (PMKSY)',
            'category' => 'Irrigation',
            'description' => 'Expanding irrigation coverage for every field (Har Khet Ko Pani) and improving water use efficiency.',
            'description_gu' => 'દરેક ખેતર માટે સિંચાઈ કવરેજ વિસ્તૃત કરવું (હર ખેત કો પાની) અને પાણીના ઉપયોગની કાર્યક્ષમતામાં સુધારો કરવો.',
            'description_hi' => 'हर खेत के लिए सिंचाई कवरेज का विस्तार करना (हर खेत को पानी) और जल उपयोग दक्षता में सुधार करना।',
            'benefits' => 'Subsidy on drip/sprinkler irrigation systems. 45-55% cost coverage.',
            'benefits_gu' => 'ટપક/ફુવારા પિયત પદ્ધતિ પર સહાય. 45-55% ખર્ચ કવરેજ.',
            'benefits_hi' => 'ड्रिप/स्प्रिंकलर सिंचाई प्रणालियों पर सब्सिडी। 45-55% लागत कवरेज।',
            'apply_link' => 'https://pmksy.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1301,
            'name' => 'National Food Security Mission (NFSM)',
            'name_gu' => 'રાષ્ટ્રીય ખાદ્ય સુરક્ષા મિશન (NFSM)',
            'name_hi' => 'राष्ट्रीय खाद्य सुरक्षा मिशन (NFSM)',
            'category' => 'Seed & Fertilizer',
            'description' => 'Promotes production of rice, wheat, pulses and coarse cereals.',
            'description_gu' => 'ચોખા, ઘઉં, કઠોળ અને બરછટ અનાજના ઉત્પાદનને પ્રોત્સાહન આપે છે.',
            'description_hi' => 'चावल, गेहूं, दालों और मोटे अनाजों के उत्पादन को बढ़ावा देता है।',
            'benefits' => 'Free/subsidized seeds, fertilizers, and micronutrients. Training support.',
            'benefits_gu' => 'નિ:શુલ્ક/સહાયવાળા બિયારણ, ખાતર અને સૂક્ષ્મ પોષકતત્વો. તાલીમ સહાય.',
            'benefits_hi' => 'निःशुल्क/सब्सिडी वाले बीज, उर्वरक और सूक्ष्म पोषक तत्व। प्रशिक्षण समर्थन।',
            'apply_link' => 'https://nfsm.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1401,
            'name' => 'Sub-Mission on Agricultural Mechanization (SMAM)',
            'name_gu' => 'કૃષિ યાંત્રીકરણ પર સબ-મિશન (SMAM)',
            'name_hi' => 'कृषि यंत्रीकरण पर उप-मिशन (SMAM)',
            'category' => 'Equipment',
            'description' => 'Capital support for selected farm machinery, implements, and custom hiring centers.',
            'description_gu' => 'પસંદ કરેલ કૃષિ મશીનરી, સાધનો અને કસ્ટમ હાયરિંગ સેન્ટર્સ માટે મૂડી સહાય.',
            'description_hi' => 'चयनित कृषि मशीनरी, उपकरणों और कस्टम हायरिंग केंद्रों के लिए पूंजी समर्थन।',
            'benefits' => '40-50% subsidy on farm equipment purchase. CHC setup assistance.',
            'benefits_gu' => 'ખેતીના સાધનોની ખરીદી પર 40-50% સહાય. CHC સેટઅપમાં મદદ.',
            'benefits_hi' => 'कृषि उपकरणों की खरीद पर 40-50% सब्सिडी। CHC सेटअप सहायता।',
            'apply_link' => 'https://agrimachinery.nic.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1501,
            'name' => 'PM Fasal Bima Yojana',
            'name_gu' => 'પીએમ ફસલ બીમા યોજના',
            'name_hi' => 'प्रधानमंत्री फसल बीमा योजना (PMFBY)',
            'category' => 'Insurance',
            'description' => 'Crop insurance scheme providing financial support to farmers suffering crop loss due to calamities.',
            'description_gu' => 'આફતોને કારણે પાક ગુમાવનારા ખેડૂતોને નાણાકીય સહાય પૂરી પાડતી પાક વીમા યોજના.',
            'description_hi' => 'अधिसूचित फसलों में से किसी के विफल होने की स्थिति में किसानों को बीमा कवरेज और वित्तीय सहायता।',
            'benefits' => 'Coverage for crop loss due to natural calamities, pests & diseases. Premium as low as 2%.',
            'benefits_gu' => 'કુદરતી આફતો, જીવાતો અને રોગોને કારણે પાકના નુકસાન માટે વીમા કવચ. પ્રીમિયમ ૨% જેટલું ઓછું.',
            'benefits_hi' => 'किसानों की आय को स्थिर करना, कृषि क्षेत्र में ऋण का प्रवाह सुनिश्चित करना।',
            'apply_link' => 'https://pmfby.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1601,
            'name' => 'Kisan Credit Card (KCC)',
            'name_gu' => 'કિસાન ક્રેડિટ કાર્ડ (KCC)',
            'name_hi' => 'किसान क्रेडिट कार्ड (KCC) योजना',
            'category' => 'Financial',
            'description' => 'Provides farmers with affordable credit for agricultural needs including crop production.',
            'description_gu' => 'ખેડૂતોને પાક ઉત્પાદન સહિતની કૃષિ જરૂરિયાતો માટે પરવડે તેવું ધિરાણ પૂરું પાડે છે.',
            'description_hi' => 'किसानों को उनकी खेती और अन्य जरूरतों जैसे इनपुट की खरीद आदि के लिए समय पर ऋण प्रदान करता है।',
            'benefits' => 'Credit up to Rs. 3 lakh at 7% interest rate (4% effective with prompt repayment).',
            'benefits_gu' => '૭% વ્યાજ દરે ૩ લાખ રૂપિયા સુધીનું ધિરાણ (સમયસર ચુકવણી સાથે ૪% અસરકારક).',
            'benefits_hi' => 'सरलीकृत ऋण वितरण, कम ब्याज दरें, लचीले पुनर्भुगतान विकल्प।',
            'apply_link' => 'https://www.myscheme.gov.in/schemes/kcc',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
        [
            'id' => 1701,
            'name' => 'PM Kisan Samman Nidhi',
            'name_gu' => 'પીએમ કિસાન સન્માન નિધિ',
            'name_hi' => 'प्रधानमंत्री किसान सम्मान निधि',
            'category' => 'Financial',
            'description' => 'Direct income support of Rs. 6,000/year to small and marginal farmers.',
            'description_gu' => 'નાના અને સીમાંત ખેડૂતોને વાર્ષિક ૬,૦૦૦ રૂપિયાની સીધી આવક સહાય.',
            'description_hi' => 'छोटे और सीमांत किसानों को प्रति वर्ष 6,000 रुपये की प्रत्यक्ष आय सहायता।',
            'benefits' => 'Rs. 6,000 per year in three equal installments of Rs. 2,000 each.',
            'benefits_gu' => 'વર્ષે ૬,૦૦૦ રૂપિયા, ૨,૦૦૦ રૂપિયાના ત્રણ સમાન હપ્તામાં.',
            'benefits_hi' => 'प्रत्येक 2,000 रुपये की तीन समान किस्तों में प्रति वर्ष 6,000 रुपये।',
            'apply_link' => 'https://pmkisan.gov.in/',
            'status' => 'Live',
            'last_updated' => date('c'),
        ],
    ];
}

function admin_demo_pesticides(): array
{
    return [
        ['id' => 201, 'name' => 'Imidacloprid 17.8% SL', 'brand' => 'Confidor', 'price_range' => 'Rs. 450 - 700', 'target_pests' => 'Aphids, whitefly, jassids, thrips', 'usage_instructions' => 'Use at label rate with thorough foliar coverage.', 'category' => 'Insecticide'],
        ['id' => 202, 'name' => 'Thiamethoxam 25% WG', 'brand' => 'Actara', 'price_range' => 'Rs. 700 - 1100', 'target_pests' => 'Whitefly, aphids, leafhoppers', 'usage_instructions' => 'Apply at early infestation stage as per label guidance.', 'category' => 'Insecticide'],
        ['id' => 203, 'name' => 'Mancozeb 75% WP', 'brand' => 'Dithane M-45', 'price_range' => 'Rs. 220 - 420', 'target_pests' => 'Early blight, late blight, downy mildew', 'usage_instructions' => 'Protective spray at recommended interval when disease pressure starts.', 'category' => 'Fungicide'],
        ['id' => 204, 'name' => 'Copper Oxychloride 50% WP', 'brand' => 'Blitox', 'price_range' => 'Rs. 260 - 460', 'target_pests' => 'Bacterial leaf spot, downy mildew, leaf spot', 'usage_instructions' => 'Apply as a preventive or early curative spray.', 'category' => 'Fungicide'],
        ['id' => 205, 'name' => 'Carbendazim 50% WP', 'brand' => 'Bavistin', 'price_range' => 'Rs. 350 - 620', 'target_pests' => 'Powdery mildew, wilt, root rot', 'usage_instructions' => 'Use for foliar spray or soil drench depending on crop and disease.', 'category' => 'Systemic Fungicide'],
        ['id' => 206, 'name' => 'Propiconazole 25% EC', 'brand' => 'Tilt', 'price_range' => 'Rs. 600 - 920', 'target_pests' => 'Rust, leaf spot, sheath blight', 'usage_instructions' => 'Apply at disease onset and repeat only as needed.', 'category' => 'Fungicide'],
    ];
}

function admin_demo_pest_mappings(): array
{
    return [
        ['mapping_id' => 301, 'pest_name' => 'Aphids', 'effectiveness' => 'High', 'pesticide_id' => 201, 'name' => 'Imidacloprid 17.8% SL', 'brand' => 'Confidor', 'price_range' => 'Rs. 450 - 700', 'target_pests' => 'Aphids, whitefly, jassids, thrips', 'usage_instructions' => 'Use at label rate with thorough foliar coverage.'],
        ['mapping_id' => 302, 'pest_name' => 'Whitefly', 'effectiveness' => 'High', 'pesticide_id' => 202, 'name' => 'Thiamethoxam 25% WG', 'brand' => 'Actara', 'price_range' => 'Rs. 700 - 1100', 'target_pests' => 'Whitefly, aphids, leafhoppers', 'usage_instructions' => 'Apply at early infestation stage as per label guidance.'],
        ['mapping_id' => 303, 'pest_name' => 'Early Blight', 'effectiveness' => 'High', 'pesticide_id' => 203, 'name' => 'Mancozeb 75% WP', 'brand' => 'Dithane M-45', 'price_range' => 'Rs. 220 - 420', 'target_pests' => 'Early blight, late blight, downy mildew', 'usage_instructions' => 'Protective spray at recommended interval when disease pressure starts.'],
        ['mapping_id' => 304, 'pest_name' => 'Bacterial Leaf Spot', 'effectiveness' => 'High', 'pesticide_id' => 204, 'name' => 'Copper Oxychloride 50% WP', 'brand' => 'Blitox', 'price_range' => 'Rs. 260 - 460', 'target_pests' => 'Bacterial leaf spot, downy mildew, leaf spot', 'usage_instructions' => 'Apply as a preventive or early curative spray.'],
        ['mapping_id' => 305, 'pest_name' => 'Powdery Mildew', 'effectiveness' => 'High', 'pesticide_id' => 205, 'name' => 'Carbendazim 50% WP', 'brand' => 'Bavistin', 'price_range' => 'Rs. 350 - 620', 'target_pests' => 'Powdery mildew, wilt, root rot', 'usage_instructions' => 'Use for foliar spray or soil drench depending on crop and disease.'],
        ['mapping_id' => 306, 'pest_name' => 'Rust', 'effectiveness' => 'High', 'pesticide_id' => 206, 'name' => 'Propiconazole 25% EC', 'brand' => 'Tilt', 'price_range' => 'Rs. 600 - 920', 'target_pests' => 'Rust, leaf spot, sheath blight', 'usage_instructions' => 'Apply at disease onset and repeat only as needed.'],
    ];
}
